"""empty message

Revision ID: 17dadfa058b5
Revises: c969e947784d
Create Date: 2022-05-25 13:19:47.095420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dadfa058b5'
down_revision = 'c969e947784d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'animal', ['species'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animal', type_='unique')
    # ### end Alembic commands ###
